
package soap.cibertec.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import soap.cibertec.interfaces.BoletaBean;
import soap.cibertec.interfaces.Cargo;
import soap.cibertec.interfaces.ComboBean;
import soap.cibertec.interfaces.Departamento;
import soap.cibertec.interfaces.DetalleBoletaBean;
import soap.cibertec.interfaces.Distrito;
import soap.cibertec.interfaces.Dna;
import soap.cibertec.interfaces.Expediente;
import soap.cibertec.interfaces.Genero;
import soap.cibertec.interfaces.Grado;
import soap.cibertec.interfaces.ObjectFactory;
import soap.cibertec.interfaces.Promotor;
import soap.cibertec.interfaces.PromotorOrigin;
import soap.cibertec.interfaces.Provincia;
import soap.cibertec.interfaces.Usuario;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "servicio", targetNamespace = "http://interfaces.cibertec.soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Servicio {


    /**
     * 
     * @param cargo
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizaCargo", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ActualizaCargo")
    @ResponseWrapper(localName = "actualizaCargoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ActualizaCargoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/actualizaCargoRequest", output = "http://interfaces.cibertec.soap/servicio/actualizaCargoResponse")
    public int actualizaCargo(
        @WebParam(name = "cargo", targetNamespace = "")
        Cargo cargo);

    /**
     * 
     * @param cargo
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertaCargo", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.InsertaCargo")
    @ResponseWrapper(localName = "insertaCargoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.InsertaCargoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/insertaCargoRequest", output = "http://interfaces.cibertec.soap/servicio/insertaCargoResponse")
    public int insertaCargo(
        @WebParam(name = "cargo", targetNamespace = "")
        Cargo cargo);

    /**
     * 
     * @param arg1
     * @param boleta
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inserta", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.Inserta")
    @ResponseWrapper(localName = "insertaResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.InsertaResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/insertaRequest", output = "http://interfaces.cibertec.soap/servicio/insertaResponse")
    public int inserta(
        @WebParam(name = "boleta", targetNamespace = "")
        BoletaBean boleta,
        @WebParam(name = "arg1", targetNamespace = "")
        List<DetalleBoletaBean> arg1);

    /**
     * 
     * @param promotor
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizaPromotor", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ActualizaPromotor")
    @ResponseWrapper(localName = "actualizaPromotorResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ActualizaPromotorResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/actualizaPromotorRequest", output = "http://interfaces.cibertec.soap/servicio/actualizaPromotorResponse")
    public int actualizaPromotor(
        @WebParam(name = "promotor", targetNamespace = "")
        Promotor promotor);

    /**
     * 
     * @param idDepartamento
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Provincia>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaProvinciaPorDepartamento", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaProvinciaPorDepartamento")
    @ResponseWrapper(localName = "listaProvinciaPorDepartamentoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaProvinciaPorDepartamentoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaProvinciaPorDepartamentoRequest", output = "http://interfaces.cibertec.soap/servicio/listaProvinciaPorDepartamentoResponse")
    public List<Provincia> listaProvinciaPorDepartamento(
        @WebParam(name = "idDepartamento", targetNamespace = "")
        int idDepartamento);

    /**
     * 
     * @param idProvincia
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Distrito>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaDistritoPorProvincia", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDistritoPorProvincia")
    @ResponseWrapper(localName = "listaDistritoPorProvinciaResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDistritoPorProvinciaResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaDistritoPorProvinciaRequest", output = "http://interfaces.cibertec.soap/servicio/listaDistritoPorProvinciaResponse")
    public List<Distrito> listaDistritoPorProvincia(
        @WebParam(name = "idProvincia", targetNamespace = "")
        int idProvincia);

    /**
     * 
     * @param idCargo
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Usuario>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaUsuarioPorCargo", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaUsuarioPorCargo")
    @ResponseWrapper(localName = "listaUsuarioPorCargoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaUsuarioPorCargoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaUsuarioPorCargoRequest", output = "http://interfaces.cibertec.soap/servicio/listaUsuarioPorCargoResponse")
    public List<Usuario> listaUsuarioPorCargo(
        @WebParam(name = "idCargo", targetNamespace = "")
        int idCargo);

    /**
     * 
     * @param dato
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Expediente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaExpeXPromotor", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaExpeXPromotor")
    @ResponseWrapper(localName = "listaExpeXPromotorResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaExpeXPromotorResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaExpeXPromotorRequest", output = "http://interfaces.cibertec.soap/servicio/listaExpeXPromotorResponse")
    public List<Expediente> listaExpeXPromotor(
        @WebParam(name = "dato", targetNamespace = "")
        int dato);

    /**
     * 
     * @param idDepartamento
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Promotor>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaPromotorPorDepartamento", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaPromotorPorDepartamento")
    @ResponseWrapper(localName = "listaPromotorPorDepartamentoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaPromotorPorDepartamentoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaPromotorPorDepartamentoRequest", output = "http://interfaces.cibertec.soap/servicio/listaPromotorPorDepartamentoResponse")
    public List<Promotor> listaPromotorPorDepartamento(
        @WebParam(name = "idDepartamento", targetNamespace = "")
        int idDepartamento);

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Departamento>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaDepartamento", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDepartamento")
    @ResponseWrapper(localName = "listaDepartamentoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDepartamentoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaDepartamentoRequest", output = "http://interfaces.cibertec.soap/servicio/listaDepartamentoResponse")
    public List<Departamento> listaDepartamento();

    /**
     * 
     * @param codigoPromotor
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Dna>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaDnaPorPromotor", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDnaPorPromotor")
    @ResponseWrapper(localName = "listaDnaPorPromotorResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDnaPorPromotorResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaDnaPorPromotorRequest", output = "http://interfaces.cibertec.soap/servicio/listaDnaPorPromotorResponse")
    public List<Dna> listaDnaPorPromotor(
        @WebParam(name = "codigoPromotor", targetNamespace = "")
        int codigoPromotor);

    /**
     * 
     * @param letra
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Promotor>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaPromotorPorCaracteres", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaPromotorPorCaracteres")
    @ResponseWrapper(localName = "listaPromotorPorCaracteresResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaPromotorPorCaracteresResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaPromotorPorCaracteresRequest", output = "http://interfaces.cibertec.soap/servicio/listaPromotorPorCaracteresResponse")
    public List<Promotor> listaPromotorPorCaracteres(
        @WebParam(name = "letra", targetNamespace = "")
        String letra);

    /**
     * 
     * @param letra
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Dna>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaDnaPorCaracteres", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDnaPorCaracteres")
    @ResponseWrapper(localName = "listaDnaPorCaracteresResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDnaPorCaracteresResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaDnaPorCaracteresRequest", output = "http://interfaces.cibertec.soap/servicio/listaDnaPorCaracteresResponse")
    public List<Dna> listaDnaPorCaracteres(
        @WebParam(name = "letra", targetNamespace = "")
        int letra);

    /**
     * 
     * @param letra
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Usuario>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaUsuarioPorCaracteres", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaUsuarioPorCaracteres")
    @ResponseWrapper(localName = "listaUsuarioPorCaracteresResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaUsuarioPorCaracteresResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaUsuarioPorCaracteresRequest", output = "http://interfaces.cibertec.soap/servicio/listaUsuarioPorCaracteresResponse")
    public List<Usuario> listaUsuarioPorCaracteres(
        @WebParam(name = "letra", targetNamespace = "")
        String letra);

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.PromotorOrigin>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaPromotorOrigin", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaPromotorOrigin")
    @ResponseWrapper(localName = "listaPromotorOriginResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaPromotorOriginResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaPromotorOriginRequest", output = "http://interfaces.cibertec.soap/servicio/listaPromotorOriginResponse")
    public List<PromotorOrigin> listaPromotorOrigin();

    /**
     * 
     * @param idDepartamento
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Dna>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaDnaPorDepartamento", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDnaPorDepartamento")
    @ResponseWrapper(localName = "listaDnaPorDepartamentoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDnaPorDepartamentoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaDnaPorDepartamentoRequest", output = "http://interfaces.cibertec.soap/servicio/listaDnaPorDepartamentoResponse")
    public List<Dna> listaDnaPorDepartamento(
        @WebParam(name = "idDepartamento", targetNamespace = "")
        int idDepartamento);

    /**
     * 
     * @param cod
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Expediente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaExpeXEstado", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaExpeXEstado")
    @ResponseWrapper(localName = "listaExpeXEstadoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaExpeXEstadoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaExpeXEstadoRequest", output = "http://interfaces.cibertec.soap/servicio/listaExpeXEstadoResponse")
    public List<Expediente> listaExpeXEstado(
        @WebParam(name = "cod", targetNamespace = "")
        int cod);

    /**
     * 
     * @param cod
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Usuario>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaLogUsuario", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaLogUsuario")
    @ResponseWrapper(localName = "listaLogUsuarioResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaLogUsuarioResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaLogUsuarioRequest", output = "http://interfaces.cibertec.soap/servicio/listaLogUsuarioResponse")
    public List<Usuario> listaLogUsuario(
        @WebParam(name = "cod", targetNamespace = "")
        String cod);

    /**
     * 
     * @param codigoUsuario
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminaUsuario", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.EliminaUsuario")
    @ResponseWrapper(localName = "eliminaUsuarioResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.EliminaUsuarioResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/eliminaUsuarioRequest", output = "http://interfaces.cibertec.soap/servicio/eliminaUsuarioResponse")
    public int eliminaUsuario(
        @WebParam(name = "codigoUsuario", targetNamespace = "")
        int codigoUsuario);

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Genero>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaGenero", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaGenero")
    @ResponseWrapper(localName = "listaGeneroResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaGeneroResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaGeneroRequest", output = "http://interfaces.cibertec.soap/servicio/listaGeneroResponse")
    public List<Genero> listaGenero();

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Usuario>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaUsuario", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaUsuario")
    @ResponseWrapper(localName = "listaUsuarioResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaUsuarioResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaUsuarioRequest", output = "http://interfaces.cibertec.soap/servicio/listaUsuarioResponse")
    public List<Usuario> listaUsuario();

    /**
     * 
     * @param usuario
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertaUsuario", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.InsertaUsuario")
    @ResponseWrapper(localName = "insertaUsuarioResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.InsertaUsuarioResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/insertaUsuarioRequest", output = "http://interfaces.cibertec.soap/servicio/insertaUsuarioResponse")
    public int insertaUsuario(
        @WebParam(name = "usuario", targetNamespace = "")
        Usuario usuario);

    /**
     * 
     * @param promotor
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertaPromotor", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.InsertaPromotor")
    @ResponseWrapper(localName = "insertaPromotorResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.InsertaPromotorResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/insertaPromotorRequest", output = "http://interfaces.cibertec.soap/servicio/insertaPromotorResponse")
    public int insertaPromotor(
        @WebParam(name = "promotor", targetNamespace = "")
        Promotor promotor);

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Distrito>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaDistrito", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDistrito")
    @ResponseWrapper(localName = "listaDistritoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDistritoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaDistritoRequest", output = "http://interfaces.cibertec.soap/servicio/listaDistritoResponse")
    public List<Distrito> listaDistrito();

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Grado>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaGrado", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaGrado")
    @ResponseWrapper(localName = "listaGradoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaGradoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaGradoRequest", output = "http://interfaces.cibertec.soap/servicio/listaGradoResponse")
    public List<Grado> listaGrado();

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Cargo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaCargo", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaCargo")
    @ResponseWrapper(localName = "listaCargoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaCargoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaCargoRequest", output = "http://interfaces.cibertec.soap/servicio/listaCargoResponse")
    public List<Cargo> listaCargo();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns soap.cibertec.interfaces.Usuario
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginId", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.LoginId")
    @ResponseWrapper(localName = "loginIdResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.LoginIdResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/loginIdRequest", output = "http://interfaces.cibertec.soap/servicio/loginIdResponse", fault = {
        @FaultAction(className = Exception.class, value = "http://interfaces.cibertec.soap/servicio/loginId/Fault/Exception")
    })
    public Usuario loginId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception
    ;

    /**
     * 
     * @param cadena
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Expediente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaExpeXCadena", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaExpeXCadena")
    @ResponseWrapper(localName = "listaExpeXCadenaResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaExpeXCadenaResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaExpeXCadenaRequest", output = "http://interfaces.cibertec.soap/servicio/listaExpeXCadenaResponse")
    public List<Expediente> listaExpeXCadena(
        @WebParam(name = "cadena", targetNamespace = "")
        String cadena);

    /**
     * 
     * @param cadena
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Cargo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaXCaracter", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaXCaracter")
    @ResponseWrapper(localName = "listaXCaracterResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaXCaracterResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaXCaracterRequest", output = "http://interfaces.cibertec.soap/servicio/listaXCaracterResponse")
    public List<Cargo> listaXCaracter(
        @WebParam(name = "cadena", targetNamespace = "")
        String cadena);

    /**
     * 
     * @param idCargo
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminaCargo", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.EliminaCargo")
    @ResponseWrapper(localName = "eliminaCargoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.EliminaCargoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/eliminaCargoRequest", output = "http://interfaces.cibertec.soap/servicio/eliminaCargoResponse")
    public int eliminaCargo(
        @WebParam(name = "idCargo", targetNamespace = "")
        int idCargo);

    /**
     * 
     * @param codigoDna
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminaDna", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.EliminaDna")
    @ResponseWrapper(localName = "eliminaDnaResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.EliminaDnaResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/eliminaDnaRequest", output = "http://interfaces.cibertec.soap/servicio/eliminaDnaResponse")
    public int eliminaDna(
        @WebParam(name = "codigoDna", targetNamespace = "")
        int codigoDna);

    /**
     * 
     * @param codigoPromotor
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminaPromotor", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.EliminaPromotor")
    @ResponseWrapper(localName = "eliminaPromotorResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.EliminaPromotorResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/eliminaPromotorRequest", output = "http://interfaces.cibertec.soap/servicio/eliminaPromotorResponse")
    public int eliminaPromotor(
        @WebParam(name = "codigoPromotor", targetNamespace = "")
        int codigoPromotor);

    /**
     * 
     * @param dna
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertaDna", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.InsertaDna")
    @ResponseWrapper(localName = "insertaDnaResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.InsertaDnaResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/insertaDnaRequest", output = "http://interfaces.cibertec.soap/servicio/insertaDnaResponse")
    public int insertaDna(
        @WebParam(name = "dna", targetNamespace = "")
        Dna dna);

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Promotor>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaPromotors", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaPromotors")
    @ResponseWrapper(localName = "listaPromotorsResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaPromotorsResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaPromotorsRequest", output = "http://interfaces.cibertec.soap/servicio/listaPromotorsResponse")
    public List<Promotor> listaPromotors();

    /**
     * 
     * @param usuario
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizaUsuario", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ActualizaUsuario")
    @ResponseWrapper(localName = "actualizaUsuarioResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ActualizaUsuarioResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/actualizaUsuarioRequest", output = "http://interfaces.cibertec.soap/servicio/actualizaUsuarioResponse")
    public int actualizaUsuario(
        @WebParam(name = "usuario", targetNamespace = "")
        Usuario usuario);

    /**
     * 
     * @param sql
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.ComboBean>
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ejecutaSQL", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.EjecutaSQL")
    @ResponseWrapper(localName = "ejecutaSQLResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.EjecutaSQLResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/ejecutaSQLRequest", output = "http://interfaces.cibertec.soap/servicio/ejecutaSQLResponse", fault = {
        @FaultAction(className = Exception.class, value = "http://interfaces.cibertec.soap/servicio/ejecutaSQL/Fault/Exception")
    })
    public List<ComboBean> ejecutaSQL(
        @WebParam(name = "sql", targetNamespace = "")
        String sql)
        throws Exception
    ;

    /**
     * 
     * @param dna
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizaDna", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ActualizaDna")
    @ResponseWrapper(localName = "actualizaDnaResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ActualizaDnaResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/actualizaDnaRequest", output = "http://interfaces.cibertec.soap/servicio/actualizaDnaResponse")
    public int actualizaDna(
        @WebParam(name = "dna", targetNamespace = "")
        Dna dna);

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Dna>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaDna", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDna")
    @ResponseWrapper(localName = "listaDnaResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaDnaResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaDnaRequest", output = "http://interfaces.cibertec.soap/servicio/listaDnaResponse")
    public List<Dna> listaDna();

    /**
     * 
     * @param usuario
     * @return
     *     returns soap.cibertec.interfaces.Usuario
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.LoginResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/loginRequest", output = "http://interfaces.cibertec.soap/servicio/loginResponse", fault = {
        @FaultAction(className = Exception.class, value = "http://interfaces.cibertec.soap/servicio/login/Fault/Exception")
    })
    public Usuario login(
        @WebParam(name = "usuario", targetNamespace = "")
        Usuario usuario)
        throws Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Expediente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaExpediente", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaExpediente")
    @ResponseWrapper(localName = "listaExpedienteResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaExpedienteResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaExpedienteRequest", output = "http://interfaces.cibertec.soap/servicio/listaExpedienteResponse")
    public List<Expediente> listaExpediente();

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Provincia>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaProvincia", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaProvincia")
    @ResponseWrapper(localName = "listaProvinciaResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaProvinciaResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaProvinciaRequest", output = "http://interfaces.cibertec.soap/servicio/listaProvinciaResponse")
    public List<Provincia> listaProvincia();

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Cargo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaCargos", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaCargos")
    @ResponseWrapper(localName = "listaCargosResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaCargosResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaCargosRequest", output = "http://interfaces.cibertec.soap/servicio/listaCargosResponse")
    public List<Cargo> listaCargos();

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Promotor>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaPromotor", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaPromotor")
    @ResponseWrapper(localName = "listaPromotorResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListaPromotorResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listaPromotorRequest", output = "http://interfaces.cibertec.soap/servicio/listaPromotorResponse")
    public List<Promotor> listaPromotor();

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Promotor>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarPromotor", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.BuscarPromotor")
    @ResponseWrapper(localName = "buscarPromotorResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.BuscarPromotorResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/buscarPromotorRequest", output = "http://interfaces.cibertec.soap/servicio/buscarPromotorResponse")
    public List<Promotor> buscarPromotor();

    /**
     * 
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Dna>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarDNA", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.BuscarDNA")
    @ResponseWrapper(localName = "buscarDNAResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.BuscarDNAResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/buscarDNARequest", output = "http://interfaces.cibertec.soap/servicio/buscarDNAResponse")
    public List<Dna> buscarDNA();

}
